# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
---
 
trigger:
  branches:
    include:
    - develop

pr:
- none
 
variables:
  isSandbox: $[eq(variables['Build.SourceBranch'], 'refs/heads/sandbox')]
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

stages:
- stage: Sandbox
  condition: eq(variables.isSandbox, true)
  jobs:
  - deployment: Landing
    pool:
      vmImage: 'ubuntu-latest'
    environment: sandbox
    strategy:                  
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: sandbox-pipeline.yaml

- stage: Develop
  condition: eq(variables.isDevelop, true)
  jobs:
  - deployment: Landing
    pool:
      vmImage: 'ubuntu-latest'
    environment: develop
    strategy:                  
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: develop-pipeline.yaml
