AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 for SRA

Parameters:
  EnvironmentName: 
    Type: String
    Default: dev
  InstanceType:
    Type: String
    Description: EC2 Instance type
  Subnet:
    Type: String
    Default: subnet-0076750448aafa5ce
  EisaiVpcId:
    Type: String
    Description: VPC id for instance
    Default: vpc-0941114977abb0bc0
  SRAAppSecurityGrpID:
    Type: String
    Description: App Security grp id for instance
    Default: SRAAppSecurityGrpID
  SSHKey: 
    Type: String
    Description: SSH key for EC2
    Default: sra-dev-ec2-key-pair
  AMIId:
    Type: String
    Description: Image id
    Default: ami-09e13647920b2ba1d
  
  
Resources:
  SRASecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/8
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/8
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 7809
          ToPort: 7809
          CidrIp: 10.135.6.16/32
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 1521
          ToPort: 1521
          CidrIp: 10.135.6.16/32
        - IpProtocol: tcp
          FromPort: 6400
          ToPort: 6400
          SourceSecurityGroupId: 
            # - !Ref "eisai-${EnvironmentName}-${AWS::Region}-SRAApp-sg"
            Fn::ImportValue:
                Fn::Sub: '${SRAAppSecurityGrpID}'
        - IpProtocol: tcp
          FromPort: 6410
          ToPort: 6410
          SourceSecurityGroupId: 
            # - !Ref "eisai-${EnvironmentName}-${AWS::Region}-SRAApp-sg"
            Fn::ImportValue:
                Fn::Sub: '${SRAAppSecurityGrpID}'
        - IpProtocol: tcp
          FromPort: 6405
          ToPort: 6405
          SourceSecurityGroupId: 
            # - !Ref "eisai-${EnvironmentName}-${AWS::Region}-SRAApp-sg"
            Fn::ImportValue:
                Fn::Sub: '${SRAAppSecurityGrpID}'
        - IpProtocol: tcp
          FromPort: 3690
          ToPort: 3690
          SourceSecurityGroupId: 
            # - !Ref "eisai-${EnvironmentName}-${AWS::Region}-SRAApp-sg"
            Fn::ImportValue:
                Fn::Sub: '${SRAAppSecurityGrpID}'
      GroupDescription: SRA ec2 Web server
      GroupName:  !Sub "eisai-${EnvironmentName}-${AWS::Region}-SRAWeb-sg"
      VpcId: !Ref EisaiVpcId
      Tags:
        - Key: Name
          Value: !Sub "eisai-${EnvironmentName}-${AWS::Region}-SRAWeb-sg"
        - Key: Environment
          Value: !Ref EnvironmentName
  WebInstance:
    Type: AWS::EC2::Instance
    DependsOn: SRASecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "eisai-${EnvironmentName}-${AWS::Region}-SRA-ESIBOWWD03"
        - Key: Environment
          Value: !Ref EnvironmentName
      ImageId: ami-05912b6333beaa478
      KeyName: !Ref SSHKey
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds: 
      - !GetAtt  SRASecurityGroup.GroupId
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 320 
          DeleteOnTermination: True
          VolumeType: gp2
  GGRepInstance:
    Type: AWS::EC2::Instance
    DependsOn: SRASecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "eisai-${EnvironmentName}-${AWS::Region}-SRA-ESIBOGGD03"
        - Key: Environment
          Value: !Ref EnvironmentName
      ImageId: ami-013675932238b286d
      KeyName: !Ref SSHKey
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds: 
      - !GetAtt  SRASecurityGroup.GroupId
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 50 
          DeleteOnTermination: True
          VolumeType: gp2
      - DeviceName: /dev/sdf
        Ebs:
          VolumeSize: 50 
          DeleteOnTermination: True
          VolumeType: gp2
  SRAAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/8
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/8
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/8 
        - IpProtocol: tcp
          FromPort: 1521
          ToPort: 1521
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 10.0.0.0/8
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 6400
          ToPort: 6400
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 6410
          ToPort: 6410
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 3690
          ToPort: 3690
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 6405
          ToPort: 6405
          CidrIp: 10.0.0.0/8
      GroupDescription: SRA ec2 App server
      GroupName:  !Sub "eisai-${EnvironmentName}-${AWS::Region}-SRAApp-sg"
      VpcId: !Ref EisaiVpcId
      Tags:
        - Key: Name
          Value: !Sub "eisai-${EnvironmentName}-${AWS::Region}-SRAApp-sg"
        - Key: Environment
          Value: !Ref EnvironmentName
  AppInstance:
    Type: AWS::EC2::Instance
    DependsOn:  SRAAppSecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "eisai-${EnvironmentName}-${AWS::Region}-SRA-ESIBOAWD03"
        - Key: Environment
          Value: !Ref EnvironmentName
      ImageId: ami-05912b6333beaa478
      KeyName: !Ref SSHKey
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds: 
      - !GetAtt  SRAAppSecurityGroup.GroupId
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 320 
          DeleteOnTermination: True
          VolumeType: gp2
Outputs:  
  SRAAppSecurityGrpID:
    Description: App Security Groups
    Value: !Ref SRAAppSecurityGroup
    Export:
      Name: SRAAppSecurityGrpID
      